-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jun 30, 2020 at 07:02 AM
-- Server version: 5.7.24
-- PHP Version: 7.2.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `coolness`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `id_adm` int(2) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `nama_adm` varchar(100) NOT NULL,
  `foto_adm` varchar(255) DEFAULT NULL,
  `moto_adm` varchar(255) NOT NULL,
  `whatsapp` varchar(15) DEFAULT NULL,
  `instagram` varchar(255) DEFAULT NULL,
  `facebook` varchar(255) DEFAULT NULL,
  `twitter` varchar(255) DEFAULT NULL,
  `youtube` varchar(255) DEFAULT NULL,
  `active` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id_adm`, `username`, `password`, `nama_adm`, `foto_adm`, `moto_adm`, `whatsapp`, `instagram`, `facebook`, `twitter`, `youtube`, `active`) VALUES
(3, 'ahauwlie@gmail.com', '$2y$10$Vd3l1Q2D1L5TijQFdparR.ku3ukH/M3X9ZmG/BFT8rUYijP/M450i', 'ahauwlie', 'http://localhost/Coolness2_CI_KOYOS/inti/images/upload/1.JPG', 'mau nyoba dulu nihh', '', '', '', '', '', 1);

-- --------------------------------------------------------

--
-- Table structure for table `barang`
--

CREATE TABLE `barang` (
  `id_bar` int(2) NOT NULL,
  `kategori_bar` varchar(50) NOT NULL,
  `nama_bar` varchar(100) NOT NULL,
  `tag_bar` varchar(50) NOT NULL,
  `harga_bar` int(9) NOT NULL,
  `size_bar` varchar(50) NOT NULL,
  `deskripsi_bar` text NOT NULL,
  `img_1_bar` varchar(255) NOT NULL,
  `img_2_bar` varchar(255) DEFAULT NULL,
  `img_3_bar` varchar(255) DEFAULT NULL,
  `img_4_bar` varchar(255) DEFAULT NULL,
  `img_5_bar` varchar(255) DEFAULT NULL,
  `img_6_bar` varchar(255) DEFAULT NULL,
  `img_7_bar` varchar(255) DEFAULT NULL,
  `img_8_bar` varchar(255) DEFAULT NULL,
  `img_9_bar` varchar(255) DEFAULT NULL,
  `img_10_bar` varchar(255) DEFAULT NULL,
  `stock_bar` int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `barang`
--

INSERT INTO `barang` (`id_bar`, `kategori_bar`, `nama_bar`, `tag_bar`, `harga_bar`, `size_bar`, `deskripsi_bar`, `img_1_bar`, `img_2_bar`, `img_3_bar`, `img_4_bar`, `img_5_bar`, `img_6_bar`, `img_7_bar`, `img_8_bar`, `img_9_bar`, `img_10_bar`, `stock_bar`) VALUES
(5, 'COBA AJA', 'Nama Barang', 'Tag 1', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/12.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(6, 'COBA AJA', 'Nama Barang', 'Tag 2', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(7, 'COBA AJA', 'Nama Barang', 'Tag 3', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(8, 'COBA AJA', 'Nama Barang', 'Tag 4', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(9, 'COBA AJA', 'Nama Barang', 'Tag 5', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(10, 'COBA AJA', 'Nama Barang', 'Tag 6', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(11, 'COBA AJA', 'Nama Barang', 'Tag 7', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/07.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(12, 'COBA AJA', 'Nama Barang', 'Tag 8', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/08.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/07.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(13, 'COBA AJA', 'Nama Barang', 'Tag 9', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/09.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/08.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(14, 'COBA AJA', 'Nama Barang', 'Tag 10', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/10.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(15, 'Coba Doang', 'Nama Barang', 'Tag 11', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/11.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(16, 'Coba Doang', 'Nama Barang', 'Tag 12', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/12.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(17, 'Coba Doang', 'Nama Barang', 'Tag 13', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(18, 'Coba Doang', 'Nama Barang', 'Tag 14', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(19, 'Coba Doang', 'Nama Barang', 'Tag 15', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(20, 'Nyoba lagi', 'Nama Barang', 'Tag 16', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(21, 'Nyoba lagi', 'Nama Barang', 'Tag 17', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(22, 'Nyoba lagi', 'Nama Barang', 'Tag 18', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(23, 'Nyoba lagi', 'Nama Barang', 'Tag 19', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/07.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(24, 'Nyoba lagi', 'Nama Barang', 'Tag 20', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/08.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(25, 'COBA AJA', 'Nama Barang', 'Tag 8', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/08.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/07.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(26, 'COBA AJA', 'Nama Barang', 'Tag 9', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/09.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/08.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(27, 'COBA AJA', 'Nama Barang', 'Tag 10', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/10.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg', NULL, NULL, NULL, NULL, NULL, 0),
(28, 'Nyoba lagi', 'Nama Barang', 'Tag 16', 250000, 'S, M, L, XL, XXL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg', NULL, NULL, NULL, NULL, NULL, 0);

-- --------------------------------------------------------

--
-- Table structure for table `blog`
--

CREATE TABLE `blog` (
  `id_blog` int(2) NOT NULL,
  `kategori_blog` varchar(50) NOT NULL,
  `judul_blog` varchar(255) NOT NULL,
  `tanggal_blog` date NOT NULL,
  `deskripsi_blog` text NOT NULL,
  `nama_admin_blog` varchar(100) NOT NULL,
  `quotes_blog` varchar(255) DEFAULT NULL,
  `quotes_author_blog` varchar(50) DEFAULT NULL,
  `img_blog` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `blog`
--

INSERT INTO `blog` (`id_blog`, `kategori_blog`, `judul_blog`, `tanggal_blog`, `deskripsi_blog`, `nama_admin_blog`, `quotes_blog`, `quotes_author_blog`, `img_blog`) VALUES
(2, '12', 'What is Lorem Ipsum? 1', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg'),
(3, '12', 'What is Lorem Ipsum? 2', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg'),
(4, '12', 'What is Lorem Ipsum? 3', '2007-01-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg'),
(5, '12', 'What is Lorem Ipsum? 4', '2007-02-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(6, '12', 'What is Lorem Ipsum? 5', '2007-03-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg'),
(7, '12', 'What is Lorem Ipsum? 6', '2007-04-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg'),
(8, '12', 'What is Lorem Ipsum? 7', '2007-05-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/07.jpg'),
(9, '12', 'What is Lorem Ipsum? 8', '2007-06-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/08.jpg'),
(10, '12', 'What is Lorem Ipsum? 9', '2007-07-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/09.jpg'),
(11, '12', 'What is Lorem Ipsum? 10', '2007-08-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/10.jpg'),
(12, '12', 'What is Lorem Ipsum? 11', '2007-09-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Coba Doang', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/11.jpg'),
(13, '12', 'What is Lorem Ipsum? 12', '2007-10-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Coba Doang', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/12.jpg'),
(14, '12', 'What is Lorem Ipsum? 13', '2007-11-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Coba Doang', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/01.jpg'),
(15, '12', 'What is Lorem Ipsum? 14', '2007-12-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Coba Doang', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/02.jpg'),
(16, '12', 'What is Lorem Ipsum? 15', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Coba Doang', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/03.jpg'),
(17, '12', 'What is Lorem Ipsum? 16', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(18, '13', 'What is Lorem Ipsum? 17', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/05.jpg'),
(19, '13', 'What is Lorem Ipsum? 18', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/06.jpg'),
(20, '13', 'What is Lorem Ipsum? 19', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/07.jpg'),
(21, '13', 'What is Lorem Ipsum? 20', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/08.jpg'),
(22, '13', 'What is Lorem Ipsum? 21', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/08.jpg'),
(23, '13', 'What is Lorem Ipsum? 22', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/09.jpg'),
(24, '13', 'What is Lorem Ipsum? 23', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'COBA AJA', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/10.jpg'),
(25, '13', 'What is Lorem Ipsum? 24', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(26, '14', 'What is Lorem Ipsum? 25', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(27, '14', 'What is Lorem Ipsum? 26', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(28, '14', 'What is Lorem Ipsum? 27', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(29, '14', 'What is Lorem Ipsum? 28', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(30, '14', 'What is Lorem Ipsum? 29', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(31, '14', 'What is Lorem Ipsum? 30', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(32, '14', 'What is Lorem Ipsum? 31', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(33, '14', 'What is Lorem Ipsum? 32', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(34, '14', 'What is Lorem Ipsum? 33', '0000-00-00', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(35, '14', 'What is Lorem Ipsum? 34', '2008-01-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(36, '14', 'What is Lorem Ipsum? 35', '2008-02-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg'),
(37, '14', 'What is Lorem Ipsum? 36', '2008-03-20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'ahauwlie', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Nyoba lagi', 'http://localhost/Coolness2_CI_KOYOS/inti/images/shop/04.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `comment`
--

CREATE TABLE `comment` (
  `id_com` int(11) NOT NULL,
  `id_blog` int(8) NOT NULL,
  `parent_id` int(11) NOT NULL,
  `comment_name` varchar(100) NOT NULL,
  `comment_email` varchar(100) NOT NULL,
  `comment_body` text NOT NULL,
  `comment_state` tinyint(1) NOT NULL,
  `comment_created` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `comment`
--

INSERT INTO `comment` (`id_com`, `id_blog`, `parent_id`, `comment_name`, `comment_email`, `comment_body`, `comment_state`, `comment_created`) VALUES
(1, 3, 0, '123', '123@gmail.com', '123123', 0, 1593485679),
(2, 6, 0, '123', '123@gmail.com', '123123123', 0, 1593490958);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id_adm`);

--
-- Indexes for table `barang`
--
ALTER TABLE `barang`
  ADD PRIMARY KEY (`id_bar`);

--
-- Indexes for table `blog`
--
ALTER TABLE `blog`
  ADD PRIMARY KEY (`id_blog`);

--
-- Indexes for table `comment`
--
ALTER TABLE `comment`
  ADD PRIMARY KEY (`id_com`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id_adm` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `barang`
--
ALTER TABLE `barang`
  MODIFY `id_bar` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=29;

--
-- AUTO_INCREMENT for table `blog`
--
ALTER TABLE `blog`
  MODIFY `id_blog` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;

--
-- AUTO_INCREMENT for table `comment`
--
ALTER TABLE `comment`
  MODIFY `id_com` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
